name: JSONAPI
main: tech.v2c.minecraft.plugins.jsonApi.JsonApi
version: "1.0.0"
api: ["1.0.0"]
load: STARTUP
author: Tuisku
description: JSON Api for NukkitX
website: https://minecraft.v2c.tech/plugins